### ISSUE TITLE
Should new players need to get ShipLicenses before building anything?

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#6]
I'm worried about the entry curve for new players. In our preferred game setup, should the initial strategy require you to get Licenses from a CP before you can build anything? Or can you personally support a small number of unlicensed things (a small platform, miner, fighter)? 

The former would be a lot simpler to implement, but might be too difficult for new players and cause them to angrily leave. I understand that Conquest is always going to be an additional challenge for people, but if it's implemented with a super steep learning curve you will probably see much less server adoption.

The latter would be easier on new players, but would require us to create at least one new `UNLICENSED` class and keep track of how many of that class each player had. A lot more work.

**Comment by stackcollision** [comment]
Because the server will track the composition of fleets internally it will be easy to allow each faction to have a number of `HullClass.CLASS.UNLICENSED` ship.  The Unlicensed beacons require no ship licenses to build and have a block count similar to corvettes.  You still need to have a beacon because of the broadcast range requirement for capturing a CP.

e: I should note that the Unlicensed type was already planned, just not committed yet.

**Comment by zrisher** [comment]
Awesome, sounds perfect.
