### ISSUE TITLE
Too difficult for new players

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#69]
Three people have complained that they have no shot of competing for ship licenses when first starting out and are thus screwed. If we have one or two static weapons on the spawn ship with a bit of ammo, or a second spawn ship geared towards combat instead of industry, it would be illustrative of how to get going and encourage people to go get into combat.

**Comment by zrisher** [comment]
I amended the title to reflect the broader issue we're trying to deal with here - basically, even with good info, there's a general feeling that it's too difficult for new players to compete with established ones for licenses. There's a lot of ways we could address this, and the issue itself is highly qualitative, so this is going to need some discussion.

A few options that might help:
- adding static weapons to spawn ships
- allowing an extra unlicensed ship per fleet
- having more CPs by default
- giving people some licenses in their spawn ship (has been suggested but I'm pretty against because very easy to abuse)
- creating a combat-focused spawn ship
- others???
- Decrease CP tick from 15 min to 5 min (with corresponding reward decrease)
- Spawn the SL in a floating cargo container instead of in a winner's inventory

The most direct current analog I can think of is Rust - you need to get into Rad Towns to get the blueprints for guns, but you can't easily survive in Rad Towns without guns if there's someone there.  But in Rust you can run in, grab them, and run out without engaging if you're super sneaky or lucky. Here, because reward distribution is directly tied to class, you literally cannot get them without displacing everyone with a larger fleet than you.

We need to find a solution that gives new players the most fun experience while still giving incumbents the advantage they deserve.

**Comment by chickenbranches** [comment]
Well i strongly think a third unlicensed is necessary for new players. You don't want to bring your little starter station with some production or your drill ship to middle so you need a third one for combat. I like the idea of the floating cargo for the time when no one is there. Maybe code it so that if no faction wins, do that. The below idea copied from the google doc could also help with this if it gives the more active players something to do elsewhere. 

Possible addition and answer to victory condition. Be able to build a “Conquest area” beacon that will cost a decent amount of ship license. These beacons can give a small amount of license like 5 an hour or even less. Main purpose would be for victory. Restrict them so that you can’t build one within the region of another that you have. Once a player has x number of beacons or x amount of space covered by the regions of said beacons turned on continuously for x number of hours/days then they win. This could also just be an addition for those players that have spare license to spend and want to have fun trying to conquer space and have nothing to do with a win condition.

Bad Trip also just suggested the idea of a public station for new players but I personally have never been of a fan of those but if it helps them then thats cool.

**Comment by zrisher** [comment]
Raideur Ng: having more CPs by default
Raideur Ng: Decrease CP tick from 15 min to 5 min (with corresponding reward decrease)
Raideur Ng: Those two are the biggest and best in my opinion

**Comment by chickenbranches** [comment]
Zeus: Make it so that everyone at the conquest point at the time gets license. Possibly based on grid values.

**Comment by zrisher** [comment]
Zeus: Faster rate of getting license will be needed if we want more players on the server. Make it to where everyone at the conquest point gets license based on value of their grids. Higher grids get more. Public trading station to trade license for ore or possibly ship designs.Public station can also have production stuff or something.
Chickenbranches: also, does the timer not restart when no one is online. I feel like leaving a ship in center while offline is not yielding nearly as many license as it should.

**Comment by zrisher** [comment]
I did a number of things to fix this:
- adding static weapons to spawn ships (2 now allowed, as a ship in #79)
- allowing an extra unlicensed ship per fleet - added 1
- having more CPs by default - added some minor CPs
- creating a combat-focused spawn ship (moved to #79)
- Decrease CP tick from 15 min to 5 min (with corresponding reward decrease) - done
- Spawn the SL in a floating cargo container instead of in a winner's inventory - moved to #80
